"""
Procedural sleep audio generation — no API, no cost.

Generates mathematically precise sleep/ambient audio:
  brown_noise    — warm rumbling noise, perfect for deep sleep
  binaural       — two sine waves slightly offset (delta 2Hz, theta 6Hz)
  drone_432hz    — 432Hz tuned ambient with slow harmonic layers
  rain           — procedural rain texture with distant thunder rumble

Output: 5-min MP3 looped by FFmpeg to fill the hour.
Cost: $0.00 (just numpy math)
"""

import os
import wave
import struct
import array
import math
import random
import tempfile
import subprocess
from typing import List

SAMPLE_RATE  = 44100
CLIP_SECONDS = 300   # 5 min — looped to 1hr by FFmpeg


def generate_sleep_audio(channel_slug: str, dest_path: str) -> str:
    """
    Generate the right sleep audio type for the given channel slug.
    Saves as MP3 to dest_path. Returns dest_path.
    """
    print(f"  [sleep] Generating procedural audio for {channel_slug}...")

    if "binaural" in channel_slug:
        samples = _binaural_beats(CLIP_SECONDS, carrier=100.0, beat_freq=2.0)
    elif "432hz" in channel_slug:
        samples = _drone_432hz(CLIP_SECONDS)
    elif "rain" in channel_slug:
        samples = _rain(CLIP_SECONDS)
    elif "baby" in channel_slug:
        samples = _lullaby_drone(CLIP_SECONDS)
    else:
        # Default: warm brown noise — deep-sleep, sleep-meditation, nature-sounds etc.
        samples = _brown_noise(CLIP_SECONDS)

    # Write to WAV then convert to MP3 via FFmpeg
    wav_path = dest_path.replace(".mp3", ".wav")
    _write_wav(samples, wav_path)
    _wav_to_mp3(wav_path, dest_path)
    os.remove(wav_path)

    size = os.path.getsize(dest_path) / 1024 / 1024
    print(f"  [sleep] Audio saved ({size:.1f} MB)")
    return dest_path


# ── Generators ─────────────────────────────────────────────────────────────────

def _brown_noise(duration: int) -> List[float]:
    """
    Brown noise (1/f² spectrum) — warm, deep rumble. Best for sleep.
    Generated by integrating white noise and normalizing.
    """
    n = duration * SAMPLE_RATE
    # Leaky integrator — each sample is prev * leak + white_noise
    leak = 0.998
    samples = []
    val = 0.0
    for _ in range(n):
        val = val * leak + (random.random() * 2 - 1) * (1 - leak)
        samples.append(val)
    return _normalize(samples)


def _binaural_beats(duration: int, carrier: float = 100.0, beat_freq: float = 2.0) -> List[float]:
    """
    Binaural beats — left ear hears carrier, right hears carrier + beat_freq.
    Brain perceives the difference as a beat at beat_freq Hz (delta = 2Hz for deep sleep).
    Layered over soft brown noise for comfort.
    """
    n = duration * SAMPLE_RATE
    noise = _brown_noise(duration)

    left  = []
    right = []
    for i in range(n):
        t = i / SAMPLE_RATE
        # Fade in/out over first/last 5 seconds
        env = _envelope(i, n, fade_samples=5 * SAMPLE_RATE)
        l = math.sin(2 * math.pi * carrier * t) * env
        r = math.sin(2 * math.pi * (carrier + beat_freq) * t) * env
        # Mix: 60% binaural tone, 40% brown noise
        left.append(l * 0.6 + noise[i] * 0.4)
        right.append(r * 0.6 + noise[i] * 0.4)

    # Interleave L/R for stereo
    stereo = []
    for l, r in zip(_normalize(left), _normalize(right)):
        stereo.append(l)
        stereo.append(r)
    return stereo


def _drone_432hz(duration: int) -> List[float]:
    """
    432Hz healing frequency — fundamental + slow harmonic layers.
    Very slow tremolo to feel alive without being distracting.
    """
    n = duration * SAMPLE_RATE
    freqs    = [432.0, 864.0, 216.0, 648.0]  # fundamental + octaves
    volumes  = [1.0,   0.4,   0.3,   0.2]
    samples  = []

    for i in range(n):
        t   = i / SAMPLE_RATE
        env = _envelope(i, n, fade_samples=8 * SAMPLE_RATE)
        # Very slow tremolo (0.05Hz = one pulse per 20s)
        tremolo = 0.85 + 0.15 * math.sin(2 * math.pi * 0.05 * t)
        val = 0.0
        for freq, vol in zip(freqs, volumes):
            # Slight detuning per harmonic for warmth
            detune = 1 + random.gauss(0, 0.0001)
            val += math.sin(2 * math.pi * freq * detune * t) * vol
        samples.append(val * env * tremolo)

    return _normalize(samples)


def _rain(duration: int) -> List[float]:
    """
    Procedural rain: filtered white noise bursts (drops) over a steady
    brown-noise base (rainfall texture), with occasional low rumble (thunder).
    """
    n = duration * SAMPLE_RATE
    base = _brown_noise(duration)

    samples = []
    # Low-pass filter state
    lp = 0.0
    lp_coef = 0.05  # cutoff — lower = softer rain

    for i in range(n):
        white = random.random() * 2 - 1
        # Low-pass filter white noise → rain texture
        lp = lp + lp_coef * (white - lp)
        # Occasional drops: random amplitude spikes
        drop = random.random() ** 20 * random.random() * 2
        val = lp * 0.7 + drop * 0.15 + base[i] * 0.15
        samples.append(val)

    return _normalize(samples)


def _lullaby_drone(duration: int) -> List[float]:
    """
    Gentle lullaby drone for baby-sleep — soft, warm, very slow oscillation.
    """
    n = duration * SAMPLE_RATE
    samples = []
    base_freq = 220.0  # A3 — warm and soothing

    for i in range(n):
        t   = i / SAMPLE_RATE
        env = _envelope(i, n, fade_samples=10 * SAMPLE_RATE)
        # Very slow rock (0.03Hz ≈ once per 33s)
        rock = 0.8 + 0.2 * math.sin(2 * math.pi * 0.03 * t)
        val  = (
            math.sin(2 * math.pi * base_freq * t) * 1.0 +
            math.sin(2 * math.pi * base_freq * 2 * t) * 0.3 +
            math.sin(2 * math.pi * base_freq * 0.5 * t) * 0.5
        )
        samples.append(val * env * rock)

    return _normalize(samples)


# ── Helpers ────────────────────────────────────────────────────────────────────

def _envelope(i: int, n: int, fade_samples: int) -> float:
    """Linear fade in/out."""
    if i < fade_samples:
        return i / fade_samples
    if i > n - fade_samples:
        return (n - i) / fade_samples
    return 1.0


def _normalize(samples: List[float], peak: float = 0.85) -> List[float]:
    """Scale samples so the peak is at `peak`."""
    mx = max(abs(s) for s in samples)
    if mx == 0:
        return samples
    scale = peak / mx
    return [s * scale for s in samples]


def _write_wav(samples: List[float], path: str, channels: int = 1):
    """Write float samples [-1, 1] to a 16-bit WAV file."""
    # Auto-detect stereo (interleaved) vs mono
    ch = 2 if len(samples) % 2 == 0 and channels == 1 and len(samples) > SAMPLE_RATE * 2 else 1
    # If binaural, samples are interleaved stereo
    is_stereo = (ch == 2 and len(samples) == CLIP_SECONDS * SAMPLE_RATE * 2)

    if is_stereo:
        n_frames = len(samples) // 2
        wav_channels = 2
    else:
        n_frames = len(samples)
        wav_channels = 1

    with wave.open(path, 'w') as wf:
        wf.setnchannels(wav_channels)
        wf.setsampwidth(2)  # 16-bit
        wf.setframerate(SAMPLE_RATE)
        packed = array.array('h', [int(s * 32767) for s in samples])
        wf.writeframes(packed.tobytes())


def _wav_to_mp3(wav_path: str, mp3_path: str):
    """Convert WAV to MP3 using FFmpeg."""
    from pipeline.create_video import get_ffmpeg_binary
    result = subprocess.run([
        get_ffmpeg_binary(), "-y", "-i", wav_path,
        "-c:a", "libmp3lame", "-b:a", "192k", "-ar", str(SAMPLE_RATE),
        mp3_path,
    ], capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"WAV→MP3 failed:\n{result.stderr[-500:]}")
